### ISSUE TITLE
Changing property value by typing objects name without opening a dialog

### ISSUE THREAD

**Issue by CrushBy** [lsfusion/platform#2] opened 2018-06-14 10:11 UTC
Here is an example how this can be done :
![image](https://user-images.githubusercontent.com/40161740/41406193-71d77248-6fd4-11e8-868c-aa88d721fd13.png)

**Comment by AlexKirkouski** [comment] 2020-01-24 09:02
Duplicate of #134

**Closed by AlexKirkouski** 2020-01-24 09:02 UTC
